#  Nepali Custom Password Generator
#  
#  <NCPG>  Copyright (C) <2019>  <Hemanta Pokharel>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.


from termcolor import colored
import random
from Core.colour import color
from Core.banners import banner
from Core.func import clean_terminal
from Core.colour import *


def home_text():
	
	print(colored("[---]","blue") + "	 " + colored(color.bold + "NEPALI CUSTOM PASSWORD GENERATOR","blue") + " " + colored(color.bold + "(NCPG)","yellow")+"     "+colored("[---]","blue"))

	print(colored("[---]","blue") + colored(color.bold + "	 Created By : ","blue") + colored(color.bold + "Hemanta Pokharel","red")+ " " + colored(color.bold + "(H9)","yellow") + "          " + colored("[---]","blue"))

	print(colored(color.bold + "                        version : ","blue") + colored(color.bold + "1.0","red"))

	print(colored("[---]","blue") + colored(color.bold + "    Fb/Gmail : ","blue") + colored(color.bold + "Hemanta.pokharel.99@gmail.com","yellow") + "    " + colored("[---]","blue"))
	
	print(colored("       Welcome To Nepali Custom Password Generator. \n          Generate common weak nepali passwords.","magenta"))
	print(colored("\n     Update NCPG from here: ","white") + colored("https://github.com/Hemant-H9/NCPG","yellow"))


#Main menu
def option_main():


	print(color.green + "\n [ Options ] ")
	print("\n   1) Generate Passwords")
	print("   2) Update NCPG configuration")
	print("   3) Install/Uninstall")
	print("   4) Help and About")
	print("   "+ colored("5) Exit","red"))
	
#Help and About option
help_about1 = \
'''
  Nepali Custom Password Generator (NCPG) is a tool which generates custom wordlists. It 
  generates weak and common wordlists containing nepali names,surnames,places,phone number etc.
  
  NCPG can be used in legal penetration tests like Dictionary attack to check your
  password strength.You can use any password cracking tool like aircrack-ng,JTR etc.
  
  [Built and tested for/in Linux only.]
  
  Three are three modes in NCPG:
  
  1.Interactive Mode
  ------------------
    
    NCPG uses CUPP for interactive mode. In this mode you
    will be asked some information about victim and generate password using it.
  
  2.Dictionary Mode
  -----------------
    
    NCPG contains some dictionaries containing nepali names,castes,places and common passwords.
    I have found many people simply using there names,places etc as a passwordjust by appending 
    something at last. In this mode NCPG generates password by modifying the dictionaries.
    
  3.Phone Number Mode
  -------------------
    
    NCPG uses Crunch to generate phone numbers.
    
    I have also found many people using their phone numbers as passwords. In this mode, you can simply
    generate phone numbers of different telecom service like ncell,ntc,sky etc.
    
    Phone numbers have high chance to be password. But, it highly increases the number of wordlists 
    and hence increases the time. It also increases time to generate passwords.
    
    Good News: I got the ncell number pattern for different zones which helps a lot to decrease the number 
    of wordlists. Only Ncell numbers will be generated by default. But, Just by editing settings
    in configuration file you can generate phone number of your wish.
    
  4.Common Password Mode
  ----------------------
    
    This mode will not appear because it is on by default. In this mode some common passwords used over inernet 
    will be included in the wordlists.
 '''
 
help_about2 = \
'''
  1. Institute of Science & Technology    [https://www.tuiost.edu.np]
  2. IOE Entrance Results                 [https://github.com/amitness/ioe]
  3. Ministry of Education                [http://www.moe.gov.np]
  4. Nepal Engineer's Association         [http://www.neanepal.org.np] 
  5. Wikipedia                            [https://en.wikipedia.org/wiki/List_of_cities_in_Nepal] 
  6. Wikipedia                            [https://en.wikipedia.org/wiki/Wikipedia:10,000_most_common_passwords]  
  7. Wikipedia                            [https://en.wikipedia.org/wiki/List_of_village_development_committees_of_Nepal]
  8. Ncell                                [https://www.ncell.axiata.com/Mobile/Useful-Info/Ncell-Number-Range]  
'''
 
help_about3 = \
'''
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program . 
  
'''

help_about4 = \
'''
  Installing NCPG is optional.For easy execution install NCPG,so
  that you can execute NCPG by typing 'ncpg' anywhere in terminal.
  
  You can use third option in NCPG to install or uninstall NCPG
  Or,
  You can install manually.
'''

configuration_text = \
'''
  There are no option to configure NCPG within it.So,you have to edit the 
  configuration file of NCPG which is 'config.ini' inorder to edit the settings.

  You can use your favourite text editor.
  Or,
  You can use second option in NCPG (Uses Nano by default) to reset or edit configuration file.
  
  Note: You can also just delete the configuration file to reset it.
''' 

def help_about():
	print(colored("\n\n About","yellow"))
	print(colored(" -----","yellow"))
	print(colored(help_about1,"cyan"))
	
	print(colored("\n Configuration","yellow"))
	print(colored(" -------------","yellow"))
	print(colored(configuration_text,"red"))
	
	print(colored("\n Install or Uninstall","yellow"))
	print(colored(" --------------------","yellow"))

	print(colored(help_about4,"white"))
	print(colored("  Usage: $ sudo bash install.sh --install | --uninstall","magenta"))

		
	print(colored("\n\n Data Sources","yellow"))
	print(colored(" ------------","yellow"))
	print(colored(help_about2,"blue"))		

	print(colored("\n License","yellow"))
	print(colored(" -------","yellow"))
	print(colored(help_about3,"magenta"))
	
def exitt():
	print(colored("\n[+] Thanks for using Nepali Custom Password Generator.\n","yellow"))
	print(colored("[-] Exiting...\n","red"))
	exit()
	
def text_config():
	clean_terminal()
	banner()
	home_text()
	print(color.green + "\n [ Options ] ")
	print("\n   1) Edit Configuration")
	print("   2) Reset to Default")
	print(colored("   3) Return to main menu","red"))

def text_reset_conf():
	print(color.green + "\n [ Options ] ")
	print("\n   1) Edit Configuration")
	print("   2) Reset to Default")
	print("\n[+] Configuration file reset to default.")
	input(color.NC+"\nPress {return} to continue...")
	
def text_install():
	print(color.green + "\n [ Options ] ")
	print("\n   1) Install")
	print("   2) Uninstall")
	print(colored("   3) Return to main menu","red"))

def opt_help_about():
	clean_terminal()
	banner()
	home_text()
	help_about() 
	input(color.NC+"Press {return} to continue...")
	clean_terminal()
	banner()
	home_text()
	option_main()
	
zones=\
'''1.Mechi	   2.Koshi     3.Sagarmatha

4.Janakpur 5.Narayani  6.Bagmati

7.Gandaki  8.Lumbini   9.Dhaulagiri

10.Rapti   11.Karnali  12.Bheri	

13.Seti	   14.Mahakali
'''


